# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d758f21468a2d24f73d2bbb55f5142ac1eb88179f588b7147b783d565a4fb6436c491634fc7f79ce1d817a83db85acc54639c7a10eb36199bdef1747866b0457

test:
  secret_key_base: f37222ab77e8bf24f1895152d5ae26f23f22ea8454f63e6dafbd677b73155836ac1dd0c5f8d2536815e8b921e3a96996f14260713a29ffa90c884da76b207b70

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
